# Generated by Django 4.2.23 on 2025-06-20 15:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Naam')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Biografie')),
                ('birth_year', models.IntegerField(blank=True, null=True, verbose_name='Geboortejaar')),
                ('death_year', models.IntegerField(blank=True, null=True, verbose_name='Sterfjaar')),
            ],
            options={
                'verbose_name': 'Auteur',
                'verbose_name_plural': 'Auteurs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Naam')),
            ],
            options={
                'verbose_name': 'Categorie',
                'verbose_name_plural': 'Categorieën',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Naam')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Tekst van de quote')),
                ('source', models.CharField(blank=True, max_length=255, null=True, verbose_name='Bron')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Jaar')),
                ('url', models.URLField(blank=True, max_length=2000, null=True, verbose_name='URL Bron')),
                ('added_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Toevoegingsdatum')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='quotes_app.author', verbose_name='Auteur')),
                ('categories', models.ManyToManyField(blank=True, related_name='quotes', to='quotes_app.category', verbose_name='Categorieën')),
                ('tags', models.ManyToManyField(blank=True, related_name='quotes', to='quotes_app.tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Quote',
                'verbose_name_plural': 'Quotes',
                'ordering': ['-added_date'],
            },
        ),
    ]
